name: Bun CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antongolub/action-setup-bun@v1.12.8 
        with:
          bun-version: v1.x # Uses latest bun 1
      - run: bun i -D
      - run: bun x jsr add @cross/test @std/assert
      - run: |
          shopt -s globstar
          for test in **/*.test.ts; do bun test $test || exit 1; done
